@startuml

skinparam componentStyle rectangle
skinparam packageStyle rectangle
top to bottom direction

frame "bdd tetris" {
    [tetris] <<block>>
    [Arduino Atmega2560] <<block>>
    [SD Card] <<block>>

    package ITDB02 as "ITDB02 Arduino Header" {
        [SD Cardreader] <<block>>
        [XPT2046] <<block>>
        [ILI9341] <<block>>
        [Display] <<block>>
    }

    tetris *--- [Arduino Atmega2560]
    tetris *--- ITDB02
    ILI9341 --> Display
    [SD Cardreader] --> [SD Card]
}

@enduml