@startuml
hide circle
skinparam linetype polyline
top to bottom direction

frame "cd tetris" {
    package colors {}
    class graphics {
        + DisplayGameOver(): void
        + RenderBackground(): void
        + InitGraphics(): void
        + InitTetrisGraphics(): void
        + RenderGame(Shape*, size_t): void
        + RenderText(char*, size_t, size_t, size_t, Color, Color): void
    }
    package shapes {}
    class tetris {
        RunTetris(): void
    }
    class timer {
        bool IsTimerComplete
        StartTimer(double): void
    }
    class menu {
        RunMenu(): void
    }
    package font8x8_basic {}
    package IL19341 {}
    package XPT2046 {}
    package SD {}
    package models {}

    menu --> tetris
    menu -> graphics
    menu --> XPT2046
    menu --> SD
    tetris -down-> shapes
    tetris -down-> graphics
    tetris --> SD
    graphics --> IL19341
    graphics --> font8x8_basic
    tetris --> timer
    tetris -> XPT2046

    note right of models #ffffff
        Common type definitions
        and models
    end note
}
@enduml