@startuml
    
    [*] --> INIT
    INIT -> UPDATE_GRAPHICS
    UPDATE_GRAPHICS --> READY_FOR_INPUT
    READY_FOR_INPUT --> TRY_PUSH_DOWN

    TRY_PUSH_DOWN --> UPDATE_GRAPHICS
    TRY_PUSH_DOWN --> CREATE_NEW_SHAPE

    CREATE_NEW_SHAPE --> UPDATE_GRAPHICS
    CREATE_NEW_SHAPE --> GAME_OVER

    state CREATE_NEW_SHAPE {
        [*] --> STATE1
        STATE1 --> STATE2
    }

@enduml