@startuml
hide footbox
skinparam shadowing false

mainframe Sequence: Reading XPT2046 with debounce timer.

participant "Mega2560 timer 3"
participant "Mega2560(Master)"
participant "XPT2046(Slave)"

"Mega2560(Master)"<<-"XPT2046(Slave)" : Touch interrupt
"Mega2560(Master)"->"Mega2560(Master)"++ : Touch ISR 
"Mega2560(Master)"-[#YellowGreen]>"Mega2560(Master)"++ : Disable touch interrupt
deactivate "Mega2560(Master)"
"Mega2560 timer 3"<<-"Mega2560(Master)" : Start


"Mega2560(Master)"->"Mega2560(Master)" ++ : Read X
"Mega2560(Master)"<<->>"XPT2046(Slave)" : Master out: Read X Command
"Mega2560(Master)"<<->>"XPT2046(Slave)" : Master in: X reading
deactivate "Mega2560(Master)"
"Mega2560(Master)"->"Mega2560(Master)" ++ : Read Y
"Mega2560(Master)"<<->>"XPT2046(Slave)" : Master out: Read Y Command
"Mega2560(Master)"<<->>"XPT2046(Slave)" : Master in: Y reading
deactivate "Mega2560(Master)"
|||
"Mega2560(Master)"<<-"XPT2046(Slave)" : Touch interrupt
note right : Immediate touch interrupts\nwill be ignored\nuntil touch interrupt is re-enabled.

"Mega2560(Master)"<<-"XPT2046(Slave)" : Touch interrupt


"Mega2560 timer 3"->>"Mega2560(Master)" : Interrupt
"Mega2560(Master)"->"Mega2560(Master)" ++ : Timer 3 ISR
"Mega2560(Master)"-[#YellowGreen]>"Mega2560(Master)" ++ : Enable touch interrupt
deactivate "Mega2560(Master)"





@enduml